spring:
  application:
    name: awesome-registry-service                    # Application name

server:
  port: 8181                                  # Port address
  
eureka:
  client:
    register-with-eureka: false               # Don't register with Eureka
    fetch-registry: false                     # Don't fetch registry details
    service-url:
     defaultZone: http://localhost:8181/eureka/
