server:
  port: 8179
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/

spring:
  application:
    name: awesome-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/batabyalsunny/awesome-app-configurations.git
          search-paths:
          - '*-service'
